import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillMail, AiFillLinkedin, AiFillGithub} from 'react-icons/ai';
import Image from "next/image";
import me from "../public/me.jpeg";


export default function Home() {
  return (
    <div className='overflow-x-hidden'>
      <Head>
        <title>matthew cheung</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 ">
        <section className='pt-48 pb-48 w-screen bg-gradient-to-r from-[#ef6543] to-[#7a8cff] relative top-[82.5px] left-0 -ml-10'>

          <nav className="bg-white py-3 fixed w-full -top-1 left-0 border-b border-gray-200 backdrop-filter backdrop-blur-md bg-opacity-20">
            <div className="container flex flex-wrap items-center justify-between ml-[225px]">
              <div className="flex order-2 mr-[225px]">
                <ul className="flex flex-row p-4 px-7 mt-0 space-x-10 text-lg font-medium">
                  <li>
                    <a href="#" className="block text-gray-700 rounded hover:bg-gray-100 hover:bg-transparent hover:text-blue-700">Home</a>
                  </li>
                  <li>
                    <a href="#" className="block text-gray-700 rounded hover:bg-gray-100 hover:bg-transparent hover:text-blue-700">About Me</a>
                  </li>
                  <li>
                    <a href="#" className="block text-gray-700 rounded hover:bg-gray-100 hover:bg-transparent hover:text-blue-700">Projects</a>
                  </li>
                </ul>
                  
                <button type="button" className="text-white bg-[#b9779a] border-2 border-[#b9779a] hover:bg-transparent hover:text-black hover:border-black ease-in-out duration-300 rounded-lg font-medium text-lg px-3.5 h-11 mr-3 mt-[7.5px] text-center">
                Resume
                </button>

              </div>

              <div className="items-center justify-between flex w-auto order-1" id="navbar-sticky">
                <ul className="flex flex-row p-4 mt-0 space-x-8 text-md font-small">
                  <li>
                    <a href="#" className="block py-2 pl-3 pr-4 text-gray-700 rounded md:p-0 ">Matthew Cheung · Sotware Engineering @ McMaster University</a>
                  </li>
                </ul>
              </div>

            </div>
          </nav>

          <div className='text-left ml-[200px] p-10'>
            <h2 className='text-[105px] py-2 text-white font-bold'>
            hi, i'm Matthew Cheung
            </h2>
            <h3 className='text-3xl -mt-[10px] mb-[30px] text-white '>a Software Engineering student at McMasterU.</h3>
            
            <button type="button" className="text-black bg-white hover:bg-transparent hover:text-white border-2 border-white ease-in-out duration-300 shadow-lg font-medium rounded-md text-2xl py-4 px-20">
              click to view my resume
            </button>
          </div>
          
        </section>
        
        <section>

          <div className='py-[330px]'>
            <div className='max-w-[1200px] mx-auto grid grid-cols-2'>

              <Image className='w-[400px] mx-auto my-auto rounded-full'src={me} /> 
              
              <div className=' shadow-xl px-5 flex flex-col justify-center'>
                <h3 className='text-3xl py-5 underline font-bold'>About me</h3>
                
                <p className='text-md py-2 leading-8 text-gray-800 '>
                  I'm a second year software engineering student @ McMaster university, 
                  currently <span className=' text-indigo-400'>looking for Summer 2023 internships. </span>
                  In the past I've worked at Code Ninjas as a Coding instructor, and have developed
                  projects such as x and x. 
                </p>

                <p className='text-md py-2 leading-8 text-gray-800'>
                  My current scope is small, but I hope to develop my skills and work on 
                  intricate and expansive projects in the future.
                </p>

              </div>
            </div>
          </div>
        </section>

        <section>
          <div className='py-64 px-4'>
            <div className='max-w-[1200px] mx-auto grid grid-cols-3'>

              <div className="max-w-xs rounded overflow-hidden shadow-lg">
                {/* <img className="w-full" src="/img/card-top.jpg" alt="Sunset in the mountains"> */}
                <div className="px-6 py-4">
                  <div className="font-bold text-xl mb-2">Project 1</div>
                  <p className="text-gray-700 text-base">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
                  </p>
                </div>

                <div className="px-6 pt-4 pb-2">
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Java</span>
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Python</span>
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Git</span>
                </div>
              </div>

              <div className="max-w-xs rounded overflow-hidden shadow-lg">
                {/* <img className="w-full" src="/img/card-top.jpg" alt="Sunset in the mountains"> */}
                <div className="px-6 py-4">
                  <div className="font-bold text-xl mb-2">Digital Logic Design</div>
                  <p className="text-gray-700 text-base">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
                  </p>
                </div>

                <div className="px-6 pt-4 pb-2">
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Verilog</span>
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Verilog Simulations</span>
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Altera Software</span>
                </div>
              </div>

              <div className="max-w-xs rounded overflow-hidden shadow-lg">
                {/* <img className="w-full" src="/img/card-top.jpg" alt="Sunset in the mountains"> */}
                <div className="px-6 py-4">
                  <div className="font-bold text-xl mb-2">Robotics Simulations</div>
                  <p className="text-gray-700 text-base">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus quia, nulla! Maiores et perferendis eaque, exercitationem praesentium nihil.
                  </p>
                </div>

                <div className="px-6 pt-4 pb-2">
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Python</span>
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Quartus Software</span>
                  <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Git</span>
                </div>
              </div>

            </div>
          </div>
        </section>

        <section>
          <div className="w-screen px-4 py-28 -ml-10 space-y-12 overflow-hidden bg-gradient-to-r from-orange-400 to-indigo-400">
            <div className="text-6xl text-white flex justify-center mt-8 gap-16">
              <AiFillLinkedin />
              <AiFillGithub />
              <AiFillMail />
            </div>

            <p className="text-base leading-6 text-center text-white">
                made by matthew cheung, 2022.
            </p>

          </div>
        </section>
      </main>
    </div>
  );
}
